// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmurfDAL;

#nullable disable

namespace SmurfDAL.Migrations
{
    [DbContext(typeof(SmurfDbContext))]
    [Migration("20260405132754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmurfBL.Entities.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("ForestId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForestId");

                    b.HasIndex("X", "Y");

                    b.ToTable("Creatures");

                    b.HasDiscriminator<string>("CreatureType").HasValue("Creature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmurfBL.Entities.Forest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Forests");
                });

            modelBuilder.Entity("SmurfBL.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForestId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForestId");

                    b.HasIndex("X", "Y");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmurfBL.Entities.BzzFly", b =>
                {
                    b.HasBaseType("SmurfBL.Entities.Creature");

                    b.Property<int>("Damage")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("BzzFly");
                });

            modelBuilder.Entity("SmurfBL.Entities.Smurf", b =>
                {
                    b.HasBaseType("SmurfBL.Entities.Creature");

                    b.Property<int>("MagicLevel")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Smurf");
                });

            modelBuilder.Entity("SmurfBL.Entities.Spider", b =>
                {
                    b.HasBaseType("SmurfBL.Entities.Creature");

                    b.Property<int>("Damage")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.Property<int>("WebStrength")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Spider");
                });

            modelBuilder.Entity("SmurfBL.Entities.Berry", b =>
                {
                    b.HasBaseType("SmurfBL.Entities.Item");

                    b.Property<int>("HealthBoost")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Berry");
                });

            modelBuilder.Entity("SmurfBL.Entities.BluePotion", b =>
                {
                    b.HasBaseType("SmurfBL.Entities.Item");

                    b.Property<int>("GlobalHealAmount")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("BluePotion");
                });

            modelBuilder.Entity("SmurfBL.Entities.RedPotion", b =>
                {
                    b.HasBaseType("SmurfBL.Entities.Item");

                    b.Property<int>("BoostAmount")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("RedPotion");
                });

            modelBuilder.Entity("SmurfBL.Entities.Sarsaparilla", b =>
                {
                    b.HasBaseType("SmurfBL.Entities.Item");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGolden")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Sarsaparilla");
                });

            modelBuilder.Entity("SmurfBL.Entities.Creature", b =>
                {
                    b.HasOne("SmurfBL.Entities.Forest", "Forest")
                        .WithMany("Creatures")
                        .HasForeignKey("ForestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forest");
                });

            modelBuilder.Entity("SmurfBL.Entities.Item", b =>
                {
                    b.HasOne("SmurfBL.Entities.Forest", "Forest")
                        .WithMany("Items")
                        .HasForeignKey("ForestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forest");
                });

            modelBuilder.Entity("SmurfBL.Entities.Forest", b =>
                {
                    b.Navigation("Creatures");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
